codegate/2024/Quals/web/master_of_calculator/server/config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  post 'calculate_fee' => 'home#calculate_fee'
end

codegate/2024/Quals/web/master_of_calculator/server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

codegate/2024/Quals/web/master_of_calculator/server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

codegate/2024/Quals/web/master_of_calculator/server/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_forgery_protection :only => [:calculate_fee]
  FILTER = ["system", "eval", "exec", "Dir", "File", "IO", "require", "fork", "spawn", "syscall", '"', "'", "(", ")", "[", "]","{","}", "`", "%","<",">"]

  def index
    render :home
  end

  def calculate_fee
      entry_price = params[:user_entry_price]
      exit_price = params[:user_exit_price]
      leverage = params[:user_leverage].to_f
      quantity = params[:user_quantity]

      if [entry_price, exit_price, leverage, quantity].map(&:to_s).any? { |input| FILTER.any? { |word| input.include?(word) } }
        response = "filtered"
      else
          response = ERB.new(<<~FORMULA
          <% pnl = ((#{exit_price} - #{entry_price}) * #{quantity} * #{leverage}).round(3) %>
          <% roi = (((#{exit_price} - #{entry_price}) * 100.0 / #{entry_price} * #{leverage})).round(3) %>
          <% initial_margin = ((#{entry_price} * #{quantity}) / #{leverage}).round(3) %>
          <%= pnl %>
          <%= roi %>%
          <%= initial_margin %>
          FORMULA
          ).result(binding)
          response = response.sub("\n\n\n","")
          pnl, roi, margin = response.split("\n")
      end
  
      render json: { response: response, pnl: pnl, roi: roi, margin: margin }

    end
end

codegate/2024/Quals/web/master_of_calculator/server/app/helpers/application_helper.rb
module ApplicationHelper
end

codegate/2024/Quals/web/master_of_calculator/server/app/helpers/home_helper.rb
module HomeHelper
end

codegate/2024/Quals/web/master_of_calculator/server/app/views/home/home.html.erb
<div class="left">
<%= form_with url: calculate_fee_path, method: :post do |form| %>
  <div class="field">
    <%= form.label :user_leverage, "Choose your leverage (1 - 125):" %>
    <%= form.range_field :user_leverage, id: 'leverage_range', min: 1,max: 125,step: 1, value: 1 %>
    <output for="leverage_range" id="leverage_output">1</output>
    <div id="leverage_values">
    </div>
  </div>

  <div class="field">
    <%= form.label :user_entry_price, "Enter your entry price:" %>
    <%= form.text_field :user_entry_price, value: 30000 %>
  </div>

  <div class="field">
    <%= form.label :user_exit_price, "Enter your exit price:" %>
    <%= form.text_field :user_exit_price, value: 31337  %>
  </div>

<div class="field">
    <%= form.label :user_quantity, "Enter you quentity:" %>
    <%= form.text_field :user_quantity, value: 1 %>
</div>
  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>
</div>
<div class="right">
    <div class="calculate_output">
        <p id="roi"></p>
        <p id="pnl"></p>
        <p id="margin"></p>
    </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    var slider = document.getElementById('leverage_range');
    var output = document.getElementById('leverage_output');
    output.innerHTML = slider.value; 

    slider.oninput = function() {
        output.innerHTML = this.value != 0 ? this.value : 1;
        
        if(this.value == 0) {
            this.value = 1; 
            output.innerHTML = 1; 
        }
    };

    var form = document.querySelector("form");
    form.addEventListener("submit", function(event) {
        event.preventDefault(); 

        const formData = new FormData(form);
        fetch("/calculate_fee", {
            method: "POST",
            body: formData,
            headers: {
                "X-Requested-With": "XMLHttpRequest",
                "Accept": "application/json"
            },
        })
        .then(response => response.json())
        .then(data => {
            if (data['response'] == "filtered") {
                document.querySelector(".calculate_output").innerHTML = "<p>no hack :p</p>"
            } else {
                document.querySelector("#roi").innerText = "ROI: " + data['roi'];
                document.querySelector("#pnl").innerText = "PnL: " + data['pnl'];
                document.querySelector("#margin").innerText = "Margin: " + data['margin'];
            }
        })
        .catch(error => console.error("Error:", error));
    });
});
</script>

codegate/2024/Quals/web/master_of_calculator/server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Master Of Calculator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>